services:
  labredes1:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8080:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN

  labredes2:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8081:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN

  labredes3:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8082:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN

networks:
  lab:
    driver: bridge
