services:
  labredes1:
    build: .
    image: labredes
    ports:
      - "8080:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./labredes1:/root/output

  labredes2:
    build: .
    image: labredes
    ports:
      - "8081:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./labredes2:/root/output

  labredes3:
    build: .
    image: labredes
    ports:
      - "8082:8080"
    networks:
      - lab
    privileged: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./labredes3:/root/output

networks:
  lab:
    driver: bridge
