services:
  labredes1:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8080:8080"
    networks:
      - lab

  labredes2:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8081:8080"
    networks:
      - lab

  labredes3:
    build:
      context: vm
      dockerfile: Dockerfile
    image: labredes
    ports:
      - "8082:8080"
    networks:
      - lab

networks:
  lab:
    driver: bridge
